//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoviesActors
    {
        public int MoviesActorsID { get; set; }
        public int MovieID { get; set; }
        public int PersonID { get; set; }
    }
}
