//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public int MoviesID { get; set; }
        public string Name { get; set; }
        public string YEAROFRELEASE { get; set; }
        public string PLOT { get; set; }
        public string PosterImage { get; set; }
        public int Producer { get; set; }
    
        public virtual Persons Person { get; set; }
    }
}
